[project]
name = "biomarkit"
version = "1.0.0"
description = "Downloads full-text scientific publications from a Scopus query and converts them into standardised Markdown."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.12,<3.14"
authors = [{ name = "Jack Bruton", email = "jack.bruton@hotmail.com" }]
dependencies = [
    "mineru[pipeline]>=3.4.0",
    "openai>=1.0.0",
    "pandas>=2.3.3",
    "playwright>=1.56.0",
    "plotly>=6.5.0",
    "pydantic>=2.12.0",
    "python-dotenv>=1.0.0",
    "requests>=2.32.5",
    "torch==2.9.1",
    "torchvision==0.24.1",
    "tqdm>=4.67.0",
    "wiley-tdm>=1.0.0",
]

[project.optional-dependencies]
dev = ["coverage>=7.11.0", "pytest>=8.4.2"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["biomarkit"]

[tool.uv]
index-strategy = "unsafe-best-match"
required-environments = [
    "sys_platform == 'win32' and platform_machine == 'AMD64'",
]

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true

[tool.uv.sources]
torch = [{ index = "pytorch-cu128" }]
torchvision = [{ index = "pytorch-cu128" }]

# Coverage settings (don't test the tests)!
[tool.coverage.run]
omit = [
    "tests/*",
    "*/tests/*",
]
[tool.coverage.report]
omit = [
    "tests/*",
    "*/tests/*",
]

# Stop coverage from running on __main__ codeblocks.
exclude_lines = [
    "if __name__ == \"__main__\":"
]
