# Contains a mapping dictionary that can be used to convert synonymous scopus publishers to a single api reference.
# Nature was acquired by Springer Publishing Group in 2015 and Nature articles are retrievable via the Springer API.
# BMC was also acquired by Springer Group and papers can be accessed via the Springer API.


publisher_map = {
    "springer": ["Springer",
                 "Springer Japan",
                 "Springer Nature",
                 "Springer Netherlands",
                 "Springer Verlag",
                 "Springer Science and Business Media Deutschland GmbH",
                 "Springer Science and Business Media B.V.",
                 "Springer Science and Business Media Deutschland GmbH info@springer-sbm.com",
                 "Springer editorial@springerplus.com",
                 "Springer Verlag service@springer.de",
                 "Springer New York LLC",
                 "Springer Netherlands rbk@louisiana.edu",
                 "Springer International Publishing",
                 "Springer Tokyo orders@springer.jp",
                 "Springer New York LLC barbara.b.bertram@gsk.com",
                 "Springer International Publishing sbfito@sbfito.com.br",
                 "Maik Nauka Publishing / Springer SBM compmg@maik.ru",
                 "Nature",
                 "Nature Research",
                 "Nature Publishing Group",
                 "Nature Publishing Group Houndmills Basingstoke, Hampshire RG21 6XS",
                 "BioMed Central Ltd",
                 "BioMed Central Ltd. info@biomedcentral.com",
                 "BioMed Central info@biomedcentral.com",
                 "BioMed Central Ltd.",
                 "BioMed Central",
                 "Kluwer Academic Publishers",
                 "Springer India"],

    "elsevier": ["Elsevier",
                 "Elsevier B.V.",
                 "Elsevier Ltd",
                 "Elsevier GmbH",
                 "Elsevier Masson s.r.l.",
                 "Elsevier Inc.",
                 "Elsevier Ireland Ltd",
                 "Elsevier Inc. usjcs@elsevier.com",
                 "Elsevier Masson s.r.l.",
                 "Elsevier Masson SAS 62 rue Camille Desmoulins Issy les Moulineaux Cedex 92442",
                 "Elsevier GmbH journals@elsevier.com",
                 "Elsevier GmbH info@urbanfischer.de",
                 "Academic Press",
                 "Academic Press Inc.",
                 "Academic Press Inc. apjcs@harcourt.com",
                 "Cell Press",
                 "KeAi Communications Co.",
                 "KeAi Publishing Communications Ltd."],

    "wiley": ["John Wiley and Sons Inc",
              "John Wiley and Sons Ltd",
              "John Wiley and Sons Inc. P.O.Box 18667 Newark NJ 07191-8667",
              "John Wiley and Sons Inc. cs-journals@wiley.com",
              "John Wiley and Sons Ltd vgorayska@wiley.com Southern Gate Chichester, West Sussex PO19 8SQ",
              "John Wiley and Sons Inc info@wiley.com",
              "John Wiley and Sons Inc.",
              "Blackwell Publishing Ltd",
              "Blackwell Publishing Ltd info@royensoc.co.uk",
              "Blackwell Publishing Ltd customerservices@oxonblackwellpublishing.com",
              "Crop Science Society of America"
              ],

    "taylor_and_francis": ["Taylor and Francis Ltd.",
                           "Taylor and Francis A.S",
                           "Taylor and Francis Ltd. michael.wagreich@univie.ac.at",
                           "Taylor and Francis Inc. customerservice@taylorandfrancis.com",
                           "Taylor and Francis Inc. 325 Chestnut St, Suite 800 Philadelphia PA 19106",
                           "Taylor and Francis Ltd healthcare.enquiries@informa.com",
                           "Taylor and Francis Ltd. diagnosis@ibn.bg",
                           ],
    "mdpi": ["MDPI",
             "Multidisciplinary Digital Publishing Institute (MDPI)",
             "MDPI AG",
             "MDPI AG diversity@mdpi.com",
             "MDPI AG rasetti@mdpi.com Postfach Basel CH-4005",
             "MDPI AG indexing@mdpi.com Postfach Basel CH-4005",
             "MDPI AG Postfach Basel CH-4005",
             "MDPI AG membranes@mdpi.com"],

    "frontiers": ["Frontiers Media S.A.",
                  "Frontiers Media SA",
                  "Frontiers Media S.A. info@frontiersin.org",
                  "Frontiers Media S.A. info@frontiersin.org c/o Michael Kenyon ch. de la Pecholettaz 6, Epalinges 1066",
                  "Frontiers Research Foundation info@frontiersin.org",
                  "Frontiers Research Foundation"
                  ],

    "plos": ["Public Library of Science",
             "Public Library of Science plos@plos.org"],

    "oxford_university_press": ["Oxford University Press",
                                "Oxford University Press jnls.cust.serv@oupjournals.org",
                                "Oxford University Press jnl.info@oup.co.uk",
                                "Genetics Society of America"],

    "american_phytopathological_society": ["American Phytopathological Society",
                                           "American Phytopathological Society 3340 Pilot Knob Road St. Paul MN 55121-2097"],

    "copernicus": ["Copernicus GmbH",
                   "Copernicus Publications",
                   "Copernicus"],

}